<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\lib\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\js\app.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\cars.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\rentals.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\renters.js" />
  </ItemGroup>

</Project>
