version: '3.8'

services:
  autonajuzapi:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
    container_name: autonajuzapi
    build:
      context: .
      dockerfile: AutoNaJuz.Api/Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:3123
      - ConnectionStrings__MsSql=Server=sqlserver,1433;Database=appDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  autonajuzweb:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
    container_name: autonajuzweb
    build:
      context: .
      dockerfile: AutoNaJuz.Web/Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:7001
      - API_BASE_URL=https://api.dev.michalo.works
    depends_on:
      - autonajuzapi

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

networks:
  app-network:
    name: app-network

volumes:
  mssql-data:
    driver: local