services:
  autonajuzapi:
    image: autonajuzapi
    container_name: autonajuzapi
    build:
      context: .
      dockerfile: AutoNaJuz.Api/Dockerfile
    ports:
      - 3123:3123
    networks:
      - sqlserver-network

  autonajuzweb:
    image: autonajuzweb
    container_name: autonajuzweb
    build:
      context: .
      dockerfile: AutoNaJuz.Web/Dockerfile
    ports:
      - 2123:2123
    networks:
      - sqlserver-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    name: sqlserver-network