services:
  autonajuzapi:
    build:
      args:
        - configuration=Release
    profiles:
      - release

  autonajuzweb:
    build:
      args:
        - configuration=Release
    profiles:
      - release

  sqlserver:
    profiles:
      - release