version: '3.4'

services:
  autonajuzapi:
    build:
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    profiles:
      - debug

  autonajuzweb:
    build:
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    profiles:
      - debug

  sqlserver:
    profiles:
      - debug
      - debug-nodocker
