version: '3.8'

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email michaloworks-domain-cert.frivolous189@aleeas.com --agree-tos --no-eff-email -d dev.michalo.works -d api.dev.michalo.works
    networks:
      - app-network
  autonajuzapi:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
    container_name: autonajuzapi
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:3123
    depends_on:
      sqlserver:
        condition: service_healthy
  autonajuzweb:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
    container_name: autonajuzweb
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:2123
    depends_on:
      - autonajuzapi
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' -N -C" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '1433:1433'
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  mssql-data:
    driver: local