version: '3.8'

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email miolszewski@outlook.com --agree-tos --no-eff-email -d dev.michalo.works -d api.dev.michalo.works
    networks:
      - app-network
  autonajuzapi:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
    container_name: autonajuzapi
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:3123
      - ConnectionStrings__MsSql=Server=sqlserver,1433;Database=appDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver
  autonajuzweb:
    image: registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
    container_name: autonajuzweb
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:7001
    depends_on:
      - autonajuzapi
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
