name: build-docker-dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build . --no-cache -f ./AutoNaJuz.Api/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
        
      - uses: actions/checkout@v4
      - name: Build Web image
        run: docker build . --no-cache -f ./AutoNaJuz.Web/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
      
      - uses: actions/checkout@v4
      - name: Push API image
        run: docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
        
      - uses: actions/checkout@v4
      - name: Push Web image
        run: docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
        
      