name: Deploy to DigitalOcean DEV
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DigitalOcean Container Registry
        run: echo "${{ secrets.DIGITAL_OCEAN_DOCKER_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DIGITAL_OCEAN_USERNAME }} --password-stdin

      - name: Build Docker images
        run: |
          docker build . --no-cache -f ./AutoNaJuz.Api/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
          docker build . --no-cache -f ./AutoNaJuz.Web/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug

      - name: Push Docker images
        run: |
          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug

      - name: Set up SSH for rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add DigitalOcean host to known_hosts to prevent host key verification
          ssh-keyscan -H ${{ secrets.DIGITAL_OCEAN_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy nginx and docker-compose.dev directories
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" ./nginx/ ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/tmp/nginx/
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" ./docker-compose.dev/ ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/tmp/docker-compose.dev/

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_SSH_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          script: |
            # Ensure /app directory exists
              mkdir -p /app

            # Move nginx/ directory to /app/nginx
              sudo mv /tmp/nginx /app/nginx

            # Move docker-compose.dev files to /app
              sudo mv /tmp/docker-compose.dev/* /app/
              sudo rm -rf /tmp/docker-compose.dev
            
            
            # Deploy the application - recreate autonajuzapi and autonajuzweb on img update, mssql, nginx and certbot should be persistent
              cd /app &&
              docker compose pull
              docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile debug stop
              docker compose -f docker-compose.yml -f docker-compose.dev.yml rm --force autonajuzweb autonajuzapi
              docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile debug up -d --no-recreate