name: Generate Doxygen Documentation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    - name: Set up Graphviz
      run: sudo apt-get install -y graphviz

    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Generate PDF from LaTeX
      run: |
        cd latex
        make

    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: docs/html

    - name: Upload PDF documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-pdf
        path: latex/refman.pdf