name: Generate Doxygen Documentation

on:
  push:
    branches:
      - '*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    - name: Set up Graphviz
      run: sudo apt-get install -y graphviz

    - name: Set up LaTeX (minimal)
      run: sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Generate PDF from LaTeX
      run: |
        if [ -d "docs/latex" ]; then
          cd docs/latex
          make
        else
          echo "LaTeX directory not found!"
          exit 1
        fi

    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: docs/html

    - name: Upload PDF documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-pdf
        path: docs/latex/refman.pdf