name: Auto Create Pull Request

on:
  push:
    branches:
      - '**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if branch matches pattern
        id: check_branch
        shell: bash
        run: |
          echo "Branch name: ${{ env.BRANCH_NAME }}"
          if [[ "${{ env.BRANCH_NAME }}" =~ ^([0-9]+)_(.+)$ ]]; then
            echo "MATCH=1" >> $GITHUB_ENV
            echo "TICKET_NO=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "SHORT_NAME=${BASH_REMATCH[2]}" >> $GITHUB_ENV
          else
            echo "MATCH=0" >> $GITHUB_ENV
          fi

      - name: Create pull request
        if: env.MATCH == '1'
        run: |
          echo "Ticket number: ${{ env.TICKET_NO }}"
          echo "Short name: ${{ env.SHORT_NAME }}"
          if gh pr view --head "${{ env.BRANCH_NAME }}" --base publish > /dev/null 2>&1; then
            echo "Pull request already exists."
          else
            gh pr create \
              --base publish \
              --head "${{ env.BRANCH_NAME }}" \
              --title "#${{ env.TICKET_NO }} ${{ env.SHORT_NAME }}" \
              --body "Automatically created pull request."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
